title: Ibon <br>Martinez-Arranz
logo: /images/imarranz.png 
description_short: GitHub Page by Ibon Martinez-Arranz
description_large: <b>Mathematician &#38; Data Scientist</b> &bull; Data Science Manager at OWL &bull; python &bull; R &bull; Jupyter &bull; pandas &bull; Scikit-Learn &bull; Big Data &bull; Machine Learning &bull; SVM &bull; Spark &bull; R Markdown &bull; ggplot2
show_ids: true
ids:
  - id1:
    name: ORCID
    href: https://orcid.org/0000-0001-9483-8426    
    ref: 0000-0001-9483-8426
  - id2: 
    name: Scopus Author ID
    href: https://www.scopus.com/authid/detail.uri?authorId=55180708800
    ref: 55180708800  
show_downloads: true

show_projects: true
projects:
  - project1:
    show: true
    name: pygenmet
    href: https://github.com/imarranz/pygenmet
    ref: Pygenmet
  - project2:
    show: true
    name: pygenmet_manual
    href: https://github.com/imarranz/pygenmet-manual
    ref: Pygenmet Manual
  - project3:
    show: false
    name: imarranz
    href: https://github.com/imarranz/imarranz
    ref: imarranz    
  - project4:
    show: true
    name: Data Science Workflow
    href: https://github.com/imarranz/data-science-workflow-management
    ref: Data Science Workflow Management
    
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page_foot: true
  is_project_page: false   
plugins:
  - jemoji
