title: Ibon<br>Martinez-Arranz
logo: /images/imarranz.png 
description_short: GitHub Page by Ibon Martinez-Arranz
description_large: Mathematician
show_downloads: true
show_projects: true
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page_foot: true
  is_project_page: false